version: '3.7'

services:
  backend:
    volumes:
      - static:/static
    build:
      context: ./nbackend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    stdin_open: true
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
      - ./path/to/default.conf:/etc/nginx/default.conf  # Dosya yolu buraya ekleyin
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend: