# Generated by Django 4.2.4 on 2023-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
